apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
    - image: luksa/kubia-unhealthy
      name: kubia
      livenessProbe:
        httpGet:
          path: /
          port: 8080